name: ${project.name}
main: ${project.mainclass}
version: ${project.version}
description: ${project.description}
author: Mics
website: https://mics.tw
api-version: 1.16

commands:
  rsp:
    description: Teleport player to Random Spawn
    usage: /rsp <player>
    permission: randomspawn.admin
    
    
permissions:
  randomspawn.admin:
    description: this can reload cupboard config
    default: op